EncompassRest/EncompassRest

AuthCode/AccessToken.cs

The _clientSecret may contain characters which need to be URL Encoded before being POSTed to the
server.

Update to add URL Encode of _clientSecret

---

src/EncompassRest/Loans/Attachments/LoanAttachments.cs
src/EncompassRest/Loans/Documents/LoanDocuments.cs
src/EncompassRest/Loans/Loans.cs

Added method overloads without the populate parameter to parallel with other methods that may add populate overloads later when supported by the Encompass API. I defaulted the methods to not populate.

Added method overloads without the populate parameter

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Contacts/Contact.cs
src/EncompassRest/Contacts/Contacts.cs
src/EncompassRest/CustomDataObjects/CustomDataObjects.cs
src/EncompassRest/EncompassRest.csproj
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Loans/LoanCustomizations.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/PublicallySerializableConverter.cs
src/EncompassRest/Token/AccessToken.cs

Fixed Loan deserialization as property
Fixed use in .NET Standard 1.x libraries
Renamed clientId and clientSecret to apiClientId and apiClientSecret
Made Loan.Initialize and Contact.Initialize public
Closes #91 
Closes #92 
Closes #97

Miscellaneous Fixes

---

src/EncompassRest.Tests/ContactsTests.cs
src/EncompassRest.Tests/GlobalCustomDataObjectsTests.cs
src/EncompassRest.Tests/TemplatesTests.cs
src/EncompassRest.Tests/TestBaseClass.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Token/AccessToken.cs
src/EncompassRest/TokenCreator.cs

Added EncompassRestClient.CreateAsync method
Made TokenExpirationHandling an optional parameter
Made TokenType always "Bearer" to support the new CreateAsync method
Fixed some tests
Closes #105

Added EncompassRestClient.CreateAsync method

---

README.md
src/EncompassRest/EncompassRestClient.cs

Obsoleted the EncompassRestClient.CreateFromUserCredentialsAsync method with a TokenExpirationHandling parameter.

Obsoleted the EncompassRestClient.CreateFromUserCredentialsAsync method

---

src/EncompassRest/LoanFolders/LoanFolders.cs

Replaced use of WebUtility.UrlEncode to Uri.EscapeDataString for the MoveLoanToFolder method
Fixes #115

MoveLoanToFolder Fix

---

src/EncompassRest.Tests/TestBaseClass.cs
src/EncompassRest/ClientParameters.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/TimeoutRetryEventArgs.cs
src/EncompassRest/Token/AccessToken.cs
src/EncompassRest/TokenCreator.cs

Adds support for auto-retry on server-side timeouts.
Adds support for specifying a timeout upon client creation through the ClientParameters parameter.
Internalizes the RequestCancellationToken in TokenCreator so users don't need to remember to pass it on.
Removes some obsolete methods.
Includes some breaking changes.
Fixes #120 
Closes #117

Adds support for auto-retry on server-side timeouts

---

README.md
src/EncompassRest.Tests/EncompassRest.Tests.csproj
src/EncompassRest/EncompassRest.csproj
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/ModelPath.cs

Changes target back to .NET Standard 1.1 from 1.3
Adds target of .NET Framework 4.6
Removed use of SslProtocols
Closes #141

Changed TLS 1.2 handling

---

src/EncompassRest.Tests/LoanConditionsTests.cs
src/EncompassRest/Comment.cs
src/EncompassRest/Company/CompensationPlan.cs
src/EncompassRest/Company/Users/User.cs
src/EncompassRest/Loans/Attachments/LoanAttachment.cs
src/EncompassRest/Loans/Conditions/LoanCondition.cs
src/EncompassRest/Loans/Conditions/PostClosingCondition.cs
src/EncompassRest/Loans/Conditions/PreliminaryCondition.cs
src/EncompassRest/Loans/Conditions/UnderwritingCondition.cs
src/EncompassRest/Organizations/LegalEntityIdentifierInformation.cs
src/EncompassRest/ResourceLocks/ResourceLock.cs
src/EncompassRest/Utilities/JsonHelper.cs

Updated conditions to always serialize `Application` or `ForAllApplications`.
Made all `EntityReference` properties not create the object upon gets.
Fixes #238

Updated conditions to always serialize Application or ForAllApplications

---

src/EncompassRest.EntityGenerator/EntityGenerator.cs
src/EncompassRest/Loans/Hmda.cs

Revert making [1395] a `StringEnumValue<State>` property. The state code should be a 2 digit numeric value stored as a string, not a state abbreviation.

Revert making [1395] a StringEnumValue<State> property

---

src/EncompassRest.Tests/BatchUpdateTests.cs
src/EncompassRest.Tests/BorrowerPairsTests.cs
src/EncompassRest.Tests/ContactNoteTests.cs
src/EncompassRest.Tests/ContactsTests.cs
src/EncompassRest.Tests/FilterTests.cs
src/EncompassRest.Tests/LoanAttachmentTests.cs
src/EncompassRest.Tests/LoanDocumentTests.cs
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest.Tests/ServicesTests.cs
src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/SerializableObject.cs
src/EncompassRest/SerializationOptions.cs
src/EncompassRest/Utilities/JsonHelper.cs

Added `ToString` overload to `SerializableObject` with `SerializationOptions` for the option to serialize only dirty elements.

Added ToString overload for dirty serialization.

---

src/EncompassRest.EntityGenerator/App.config
src/EncompassRest.EntityGenerator/EncompassRest.EntityGenerator.csproj
src/EncompassRest.EntityGenerator/packages.config
src/EncompassRest.Tests/AccessTokenTests.cs
src/EncompassRest.Tests/ApiTestAttribute.cs
src/EncompassRest.Tests/BaseApiClientTests.cs
src/EncompassRest.Tests/BorrowerPairsTests.cs
src/EncompassRest.Tests/ClientTests.cs
src/EncompassRest.Tests/ContactGroupsTests.cs
src/EncompassRest.Tests/ContactNoteTests.cs
src/EncompassRest.Tests/ContactsTests.cs
src/EncompassRest.Tests/CustomFieldDefinitionsTests.cs
src/EncompassRest.Tests/EncompassRest.Tests.csproj
src/EncompassRest.Tests/FieldReaderTests.cs
src/EncompassRest.Tests/GlobalCustomDataObjectsTests.cs
src/EncompassRest.Tests/LoanAssociateMilestoneTests.cs
src/EncompassRest.Tests/LoanAttachmentTests.cs
src/EncompassRest.Tests/LoanConditionsTests.cs
src/EncompassRest.Tests/LoanDocumentTests.cs
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/OrganizationTests.cs
src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest.Tests/ResourceLocksTest.cs
src/EncompassRest.Tests/SchemaTests.cs
src/EncompassRest.Tests/TemplatesTests.cs
src/EncompassRest.Tests/UserTests.cs
src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest.sln
src/EncompassRest/EncompassRest.csproj

Switched failing tests due to Ellie Mae to be passing tests and will then fail when they are supported by Ellie Mae.
Added `ApiTestAttribute` to exclude selected tests from live unit testing.

Switched failing tests due to Ellie Mae to be passing tests

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Calculators/Calculators.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Loans/CreateLoanOptions.cs
src/EncompassRest/Loans/LoanCustomizations.cs
src/EncompassRest/Loans/LoanOptions.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/Loans/UpdateLoanOptions.cs

Refactored transient loan update to use new loan calculation API.
This is a hard-break, i.e. no obsolete warnings for any that are currently using the `UpdateLoanOptions.Transient` property.
Closes #245

Refactored transient loan update to use new loan calculation API

---

src/EncompassRest/EncompassRest.csproj

Use `PackageLicenseExpression` due to `PackageLicenseUrl` deprecation

Use PackageLicenseExpression due to PackageLicenseUrl deprecation

---

src/EncompassRest.Tests/BaseApiClientTests.cs
src/EncompassRest/BaseApiClient.cs

Added support to the `BaseApiClient` to return anonymous types so as not to require explicitly creating a new type for simple or temporary uses.

Added anonymous type support to BaseApiClient

---

src/EncompassRest/ApiResponseEventArgs.cs
src/EncompassRest/EncompassRestException.cs

Added support for checking the api limits from the `ApiResponse` event or from an `EncompassRestException`.

Added support for checking the api limits

---

src/EncompassRest/Token/AccessToken.cs

% sign is the url escape sequence and if it occurs in your api client secret it must be url encoded. Otherwise you get this error.
```js
{
"error_description": "unable to parse Authorization header java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern",
"error": "invalid_client"
}
```
Url encoding was removed in #288 due to other issues it was causing and so this will just fix this specific case.

Fix issue with authenticating with a % sign in the api client secret.

---

src/EncompassRest/EncompassRest.csproj
src/EncompassRest/Utilities/JsonHelper.cs

Upgraded the minimum Json.NET version to fix a .NET Core issue and to support the first major version with first class .NET Standard 2.0 support.
Fixes #268

Upgraded the minimum Json.NET version to fix a .NET Core issue

---

src/EncompassRest.Tests/LoanDocumentTests.cs
src/EncompassRest/Loans/Attachments/LoanAttachment.cs

Added support for assigning an attachment to a document upon upload with the `DocumentRefId` property.
Closes #296

Added support for assigning an attachment to a document upon upload

---

src/EncompassRest.Tests/BaseApiClientTests.cs
src/EncompassRest.Tests/BorrowerPairsTests.cs
src/EncompassRest.Tests/ContactNoteTests.cs
src/EncompassRest.Tests/CustomFieldDefinitionsTests.cs
src/EncompassRest.Tests/GlobalCustomDataObjectsTests.cs
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/ResourceLocksTest.cs
src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Contacts/ContactGroups.cs
src/EncompassRest/Contacts/ContactNotes.cs
src/EncompassRest/Contacts/Contacts.cs
src/EncompassRest/CustomDataObjects/CustomDataObjects.cs
src/EncompassRest/Loans/Apis/BorrowerPairs.cs
src/EncompassRest/Loans/Associates/LoanAssociates.cs
src/EncompassRest/Loans/LoanApiObject.cs
src/EncompassRest/Loans/LoanApis.cs
src/EncompassRest/ResourceLocks/ResourceLocks.cs
src/EncompassRest/Settings/Loan/CustomFieldDefinitions.cs
src/EncompassRest/Webhook/Webhook.cs

Updated delete api's throughout to throw on unsuccessful status code and added trydelete api equivalents to the existing.
Closes #298

Updated delete api's throughout to throw on unsuccessful status code

---

src/EncompassRest.Tests/AccessTokenTests.cs
src/EncompassRest.Tests/EncompassRest.Tests.csproj
src/EncompassRest/DirtyExtensibleObject.cs
src/EncompassRest/EncompassRest.csproj
src/EncompassRest/EncompassRestClient.cs

Second attempt of adding `IAsyncDisposable` support for revoking the current access token now that CI works with .NET Core 3.0
Closes #275

Async disposable for revoking access token

---

src/EncompassRest.Tests/LoanAttachmentTests.cs
src/EncompassRest/Loans/Attachments/LoanAttachment.cs

Fix attachment initialize bug. Unit tests were already failing so no need to add more. This bug was introduced since our last NuGet package release so it's not a big deal.

Attachment initialize bug

---

src/EncompassRest/Contacts/ContactNotes.cs

Removed assignment of the NoteId when retrieving a Note as the bug has been fixed by Ellie Mae.

Removed assignment of the NoteId when retrieving a Note

---

src/EncompassRest/ApiObject.cs
src/EncompassRest/ClientParameters.cs
src/EncompassRest/EncompassRestClient.cs

ClientParameters now has a BaseAddress property that is used to set the BaseAddress value on the EncompassRestClient.  The ApiObject then uses the BaseAddress property to set its URL for API callouts.  The default value is "https://api.elliemae.com/".

A BaseAddress URL can be set for API calls

---

src/EncompassRest/Webhook/WebhookSubscription.cs

Possible solution for #363 
It was a little difficult to follow the contract resolvers for the json serialization that this project is using. so there didn't appear to be a clear override to the property name. I didn't figure that the simple [JsonPropertyAttribute](https://www.newtonsoft.com/json/help/html/JsonPropertyName.htm) would work, so instead in this PR I've just modified the name on the model. Hopefully that will suffice. If the `JsonPropertyAttribute` would work, I would recommend doing that instead though.

Fix ability to specify custom signing key when creating a webhook subscription
