AuthCode/AccessToken.cs
AuthCode/HelperStatics.cs
AuthCode/TokenResponse.cs
Documents.cs
EncompassREST.csproj
Exceptions/ExceptionClasses.cs
Exceptions/InvalidFieldException.cs
Exceptions/LoanLocked.cs
HelperClasses/HttpClientExtensions.cs
HelperClasses/RequestParameters.cs
HelperClasses/Variance.cs
JSONHelpers/JsonExtensions.cs
Loans.cs
Pipeline.cs
Reporting/Report.cs
Reports.cs
Schemas.cs
Serialization/CustomRestSharpSerializer.cs
Session.cs
Webhooks.cs
packages.config

Switched string.Format's to String Interpolation.
Used var where type is obvious.
Upgraded dependency pre-release NuGet packages to latest.
Switched to using nameof operator where appropriate.
Removed unnecessary using statements.

Fixed many naming inconsistencies.

---

AuthCode/AccessToken.cs
Documents.cs
Exceptions/ExceptionClasses.cs
HelperClasses/HttpClientExtensions.cs
HelperClasses/RequestParameters.cs
HelperClasses/Variance.cs
Loans.cs
Reporting/Report.cs
Schemas.cs
Serialization/CustomRestSharpSerializer.cs

Changed some properties and methods to being expression-bodied.

Expression-bodied properties and methods

---

src/EncompassRest.EntityGenerator/packages.config
src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest/Filters/SortOrder.cs
src/EncompassRest/Utilities/EnumJsonConverter.cs
src/EncompassRest/Utilities/EnumOutputAttribute.cs
src/EncompassRest/Utilities/JsonHelper.cs

Fixed SortOrder serialization bug

Fixed SortOrder serialization bug

---

src/EncompassRest.EntityGenerator/EntityGenerator.cs
src/EncompassRest.Tests/AccessTokenTests.cs
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest.Tests/TestBaseClass.cs

Add support for testing any environment through a json config file.
Add AccessToken tests which weren't possible before.

Add support for testing any environment

---

src/EncompassRest/LoanPipeline/LoanPipelineCursor.cs

Simplify GetItems
add flexible fields retrival

Pipeline Cursor updates

---

Guidelines.md
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest.sln
src/EncompassRest/LoanPipeline/LoanPipelineCursor.cs
src/EncompassRest/LoanPipeline/Pipeline.cs
src/EncompassRest/Loans/Attachments/LoanAttachments.cs
src/EncompassRest/Loans/Documents/LoanDocuments.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/Schema/Schema.cs
src/EncompassRest/Webhook/Webhook.cs

Closes #43.
Also fixed pipeline unit test after the refactoring.

Added support for raw query parameters

---

src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Webhook/Webhook.cs
src/EncompassRest/Webhook/WebhookSubscription.cs

Added webhook dirty checking

---

src/EncompassRest.Tests/LoanDocumentTests.cs
src/EncompassRest/Filters/DateFieldFilter.cs
src/EncompassRest/Filters/NumericFieldFilter.cs
src/EncompassRest/Filters/StringFieldFilter.cs
src/EncompassRest/Loans/Attachments/PageAnnotation.cs
src/EncompassRest/Loans/Documents/LoanDocument.cs
src/EncompassRest/Loans/Documents/LoanDocuments.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/Schema/Schema.cs
src/EncompassRest/Utilities/EnumJsonConverter.cs

Fixed support for `LoanDocument.Status`

---

src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Utilities/JsonStreamContent.cs
src/EncompassRest/Utilities/JsonStringContent.cs
src/EncompassRest/Webhook/Webhook.cs

Changed `Webhook.DeleteSubscriptionAsync` to return `Task<bool>` instead of throwing and returing just `Task`
Fixes #58

Removed adding the charset in the application/json content-type

---

src/EncompassRest.Tests/EncompassRest.Tests.csproj
src/EncompassRest/EncompassRest.csproj

updates to package location in project files.

package location update

---

src/EncompassRest.Tests/CustomDataObjectsTests.cs
src/EncompassRest.Tests/GlobalCustomDataObjectsTests.cs
src/EncompassRest/CustomDataObjects/CustomDataObject.cs
src/EncompassRest/CustomDataObjects/CustomDataObjects.cs
src/EncompassRest/CustomDataObjects/GlobalCustomDataObjects.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Loans/LoanApis.cs
src/EncompassRest/Loans/LoanCustomDataObjects.cs
src/EncompassRest/Loans/LoanCustomizations.cs
src/EncompassRest/Loans/LoanObjectBoundApis.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/Users/UserCustomDataObjects.cs
src/EncompassRest/Users/Users.cs

Added cdo support

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/ApiObject.cs
src/EncompassRest/Contacts/ContactNotes.cs
src/EncompassRest/Contacts/Contacts.cs
src/EncompassRest/CustomDataObjects/CustomDataObjects.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/LoanFolders/LoanFolders.cs
src/EncompassRest/Loans/Attachments/LoanAttachments.cs
src/EncompassRest/Loans/CreateLoanOptions.cs
src/EncompassRest/Loans/Documents/LoanDocuments.cs
src/EncompassRest/Loans/LoanApiObject.cs
src/EncompassRest/Loans/LoanApis.cs
src/EncompassRest/Loans/LoanMetadata.cs
src/EncompassRest/Loans/LoanOptions.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/Loans/UpdateLoanOptions.cs
src/EncompassRest/Webhook/Webhook.cs

Create a loan in a folder
Create a loan from a loan template
Apply a loan template to an existing loan
Move a loan from one folder to another
Retrieve metadata information from a loan
Closes #63
Still needs tests added

Loan API Enhancements

---

src/EncompassRest.Tests/TemplatesTests.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Settings/Settings.cs
src/EncompassRest/Settings/Templates/LoanTemplates.cs
src/EncompassRest/Settings/Templates/TemplateApiObject.cs
src/EncompassRest/Settings/Templates/Templates.cs

Adds LoanTemplate support.
Closes #62

Added LoanTemplate support

---

src/EncompassRest.Tests/TemplatesTests.cs
src/EncompassRest/Settings/Templates/LoanTemplateSet.cs
src/EncompassRest/Settings/Templates/Templates.cs

Renamed LoanTemplates to LoanTemplateSet

Renamed LoanTemplates to LoanTemplateSet

---

src/EncompassRest.Tests/ContactsTests.cs
src/EncompassRest.Tests/GlobalCustomDataObjectsTests.cs
src/EncompassRest.Tests/LoanAttachmentTests.cs
src/EncompassRest.Tests/TestBaseClass.cs
src/EncompassRest/ApiObject.cs
src/EncompassRest/Contacts/ContactNotes.cs
src/EncompassRest/Contacts/Contacts.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Loans/Attachments/LoanAttachment.cs
src/EncompassRest/Loans/Attachments/LoanAttachments.cs
src/EncompassRest/Loans/Attachments/MediaUrlObject.cs
src/EncompassRest/Loans/Documents/LoanDocuments.cs
src/EncompassRest/Loans/LoanApiObject.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/ResourceLocks/ResourceLocks.cs
src/EncompassRest/Token/AccessToken.cs
src/EncompassRest/Webhook/Webhook.cs

Added attachment upload support.
Closes #64

Added attachment upload support

---

src/EncompassRest.EntityGenerator/EntityGenerator.cs
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Loans/Fee.cs
src/EncompassRest/Loans/Gfe2010.cs
src/EncompassRest/Loans/Hmda.cs
src/EncompassRest/NA.cs
src/EncompassRest/Utilities/JsonHelper.cs

Changed NA to directly support null values.
Fixes #111

Changed NA to directly support null values.

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/EncompassRest.csproj
src/EncompassRest/ExtensibleObject.cs
src/EncompassRest/Extensions.cs
src/EncompassRest/Utilities/JsonHelper.cs
src/EncompassRest/Utilities/JsonStreamContent.cs

Added ToString overloads and Cloning support
Closes #112
Closes #114

ExtensibleObject ToString and Clone

---

src/EncompassRest/.editorconfig
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Token/AccessToken.cs

Added .editorconfig file, added as many warnings as possible based on Guidelines.md

Added .editorconfig to enforce Guidelines.md through warnings

---

src/EncompassRest.Tests/PipelineTests.cs

Added tests to confirm EmptyFieldFilter and NotEmptyFieldFilter now work without a value and with Numeric fields.

Added tests for EmptyFieldFilter and NotEmptyFieldFilter

---

src/EncompassRest/DirtyList.cs

Fixed DirtyList IList implementation

---

src/EncompassRest.Tests/ContactsTests.cs
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest.Tests/SchemaTests.cs
src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Contacts/BorrowerContactSelector.cs
src/EncompassRest/Contacts/BusinessContactSelector.cs
src/EncompassRest/Contacts/ContactData.cs
src/EncompassRest/Contacts/ContactListParameters.cs
src/EncompassRest/Contacts/ContactSelector.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/LoanPipeline/Pipeline.cs
src/EncompassRest/LoanPipeline/PipelineCanonicalNames.cs
src/EncompassRest/LoanPipeline/PipelineFieldDefinition.cs
src/EncompassRest/Schema/FieldDefinitionCategory.cs
src/EncompassRest/Schema/FieldDefinitionDataSource.cs
src/EncompassRest/Schema/LoanFieldFormat.cs
src/EncompassRest/Settings/Contacts/BorrowerContactsSettings.cs
src/EncompassRest/Settings/Contacts/BusinessContactsSettings.cs
src/EncompassRest/Settings/Contacts/ContactFieldDefinition.cs
src/EncompassRest/Settings/Contacts/ContactsSettings.cs
src/EncompassRest/Settings/Settings.cs
src/EncompassRest/Webhook/WebhookResource.cs
src/EncompassRest/Webhook/WebhookResourceEventObject.cs

Still need to add tests and fix `StringEnumValue` usage.
Closes #133

Contact Api Updates

---

src/EncompassRest.Tests/LoanAssociateMilestoneTests.cs
src/EncompassRest/Loans/Associates/AssignAssociateParameters.cs
src/EncompassRest/Loans/Associates/LoanAssociates.cs
src/EncompassRest/Loans/LoanApis.cs
src/EncompassRest/Loans/MilestoneFreeRoles/LoanMilestoneFreeRole.cs
src/EncompassRest/Loans/MilestoneFreeRoles/LoanMilestoneFreeRoles.cs
src/EncompassRest/Loans/Milestones/LoanMilestone.cs
src/EncompassRest/Loans/Milestones/LoanMilestones.cs

Add support for Loan Associates & Milestones.
Closes #129

Loan Associates & Milestones

---

src/EncompassRest/Contacts/ContactNotes.cs
src/EncompassRest/Contacts/Contacts.cs
src/EncompassRest/CustomDataObjects/CustomDataObjects.cs
src/EncompassRest/LoanBatch/BatchUpdate.cs
src/EncompassRest/LoanPipeline/Pipeline.cs
src/EncompassRest/Loans/Apis/BorrowerPairs.cs
src/EncompassRest/Loans/Associates/LoanAssociates.cs
src/EncompassRest/Loans/Attachments/LoanAttachments.cs
src/EncompassRest/Loans/Documents/LoanDocuments.cs
src/EncompassRest/Loans/LoanApis.cs
src/EncompassRest/Loans/Loans.cs
src/EncompassRest/Loans/MilestoneFreeRoles/LoanMilestoneFreeRoles.cs
src/EncompassRest/Loans/Milestones/LoanMilestones.cs
src/EncompassRest/ResourceLocks/ResourceLocks.cs
src/EncompassRest/Schema/Schema.cs
src/EncompassRest/Settings/Contacts/ContactsSettings.cs
src/EncompassRest/Settings/Templates/TemplateApiObject.cs
src/EncompassRest/Token/AccessToken.cs
src/EncompassRest/Webhook/Webhook.cs

Added optional queryString support to all raw methods
Removed convenience raw method overloads that configure a queryString. We should leave that to users.

Added optional queryString support to all raw methods

---

src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest/LoanPipeline/Pipeline.cs

Makes it easier to consume.
Closes #149

CreateCursor no longer returns null for no results

---

src/EncompassRest.EntityGenerator/EntityGenerator.cs
src/EncompassRest.Tests/LoanAssociateMilestoneTests.cs
src/EncompassRest/Loans/Associates/AssignAssociateParameters.cs
src/EncompassRest/Loans/Enums/LoanAssociateType.cs
src/EncompassRest/Loans/LoanAssociate.cs
src/EncompassRest/Loans/Milestones/LoanMilestones.cs
src/EncompassRest/Loans/Milestones/MilestoneAction.cs

Added support for finishing and unfinishing milestones
Fixed associate assignment
Added `LoanAssociateType` enum
Closes #148

Added support for finishing and unfinishing milestones

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/ModelPath.cs

Fix for #166

---

src/EncompassRest.Tests/FieldReaderTests.cs
src/EncompassRest/Loans/FieldReader/LoanFieldReader.cs
src/EncompassRest/Loans/FieldReader/LoanFieldValue.cs
src/EncompassRest/Loans/LoanApis.cs

Added Field Reader Support.
Closes #170

Added Field Reader Support

---

src/EncompassRest.Tests/ContactsTests.cs
src/EncompassRest/CanonicalContactField.cs
src/EncompassRest/CanonicalFieldExtensions.cs
src/EncompassRest/Contacts/ContactCursor.cs
src/EncompassRest/Contacts/ContactListParameters.cs
src/EncompassRest/Contacts/ContactLoanMatchType.cs
src/EncompassRest/Contacts/ContactSelector.cs
src/EncompassRest/Cursor.cs
src/EncompassRest/Filters/DateFieldFilter.cs
src/EncompassRest/Filters/EmptyFieldFilter.cs
src/EncompassRest/Filters/FieldSort.cs
src/EncompassRest/Filters/NotEmptyFieldFilter.cs
src/EncompassRest/Filters/NumericFieldFilter.cs
src/EncompassRest/Filters/StringFieldFilter.cs
src/EncompassRest/LoanPipeline/LoanPipelineCursor.cs

Added Contact Cursor Support

---

src/EncompassRest/EncompassRest.csproj

Enables step-through debugging of NuGet packages. See [https://github.com/dotnet/sourcelink](https://github.com/dotnet/sourcelink) for details.

Added Source Link Support

---

src/EncompassRest.Tests/LoanConditionsTests.cs
src/EncompassRest/Filters/DateFieldFilter.cs
src/EncompassRest/Filters/EmptyFieldFilter.cs
src/EncompassRest/Filters/FieldFilter.cs
src/EncompassRest/Filters/NotEmptyFieldFilter.cs
src/EncompassRest/Filters/NumericFieldFilter.cs
src/EncompassRest/Filters/OrdinalFieldMatchType.cs
src/EncompassRest/Filters/StringFieldFilter.cs
src/EncompassRest/Filters/StringFieldMatchType.cs
src/EncompassRest/Loans/Conditions/ConditionCategory.cs
src/EncompassRest/Loans/Conditions/ConditionComment.cs
src/EncompassRest/Loans/Conditions/ConditionQueryParameters.cs
src/EncompassRest/Loans/Conditions/ConditionSource.cs
src/EncompassRest/Loans/Conditions/ConditionStatus.cs
src/EncompassRest/Loans/Conditions/ConditionType.cs
src/EncompassRest/Loans/Conditions/LoanCondition.cs
src/EncompassRest/Loans/Conditions/LoanConditions.cs
src/EncompassRest/Loans/Conditions/LoanPostClosingConditions.cs
src/EncompassRest/Loans/Conditions/LoanPreliminaryConditions.cs
src/EncompassRest/Loans/Conditions/LoanUnderwritingConditions.cs
src/EncompassRest/Loans/Conditions/PostClosingCondition.cs
src/EncompassRest/Loans/Conditions/PreliminaryCondition.cs
src/EncompassRest/Loans/Conditions/PriorToMilestone.cs
src/EncompassRest/Loans/Conditions/UnderwritingCondition.cs
src/EncompassRest/Loans/LoanApis.cs

Added Loan Conditions Support

---

src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Webhook/WebhookFilters.cs
src/EncompassRest/Webhook/WebhookResourceEvent.cs
src/EncompassRest/Webhook/WebhookSubscription.cs

Added Webhook change event support and subscription filters support.
Added better WebhookSubscription constructor overloads.
Removed dirty checking for webhook subscriptions as the update method uses the PUT HTTP Verb instead of PATCH.

Added Webhook change event support and subscription filters support.

---

src/EncompassRest.Tests/ContactGroupsTests.cs
src/EncompassRest/AssignmentAction.cs
src/EncompassRest/Contacts/ContactGroup.cs
src/EncompassRest/Contacts/ContactGroupType.cs
src/EncompassRest/Contacts/ContactGroups.cs
src/EncompassRest/Contacts/ContactType.cs
src/EncompassRest/EncompassRestClient.cs

Added Contact Group Support

---

src/EncompassRest.Tests/LoanAssociateMilestoneTests.cs
src/EncompassRest/Loans/EntityCustomizations.cs
src/EncompassRest/Loans/Milestones/LoanMilestone.cs

Added milestone comments support

Added milestone comments support

---

src/EncompassRest.Tests/BaseApiClientTests.cs
src/EncompassRest/BaseApiClient.cs
src/EncompassRest/EncompassRestClient.cs

Added `BaseApiClient` support for making calls to apis that aren't currently supported by EncompassRest.
Closes #186

Added BaseApiClient support

---

src/EncompassRest/SerializableObject.cs

Made SerializableObject constructor internal

---

src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Webhook/Webhook.cs

Added support for retrieving a single Webhook Resource

---

src/EncompassRest.Tests/ContactGroupsTests.cs
src/EncompassRest/Contacts/ContactGroups.cs

Added populate support to creating and updating ContactGroups

---

src/EncompassRest.Tests/PipelineTests.cs
src/EncompassRest/LoanPipeline/Pipeline.cs

Added support for the ignoreInvalidFields query parameter for the loan pipeline.
Closes #191

Added support for the ignoreInvalidFields query parameter

---

src/EncompassRest.Tests/ClientTests.cs
src/EncompassRest/ApiResponseEventArgs.cs
src/EncompassRest/ClientParameters.cs
src/EncompassRest/EncompassRestClient.cs

Added support for an api response event

---

src/EncompassRest.Tests/LoanAttachmentTests.cs
src/EncompassRest/Loans/Attachments/LoanAttachment.cs
src/EncompassRest/Loans/Attachments/LoanAttachments.cs
src/EncompassRest/NeverSerializeValue.cs

Added support for GetAttachment's generateURL query parameter

---

src/EncompassRest.Tests/SchemaTests.cs
src/EncompassRest/Schema/Schema.cs

Added Path Generator api support

---

src/EncompassRest.Tests/SchemaTests.cs
src/EncompassRest/Loans/LoanCustomizations.cs
src/EncompassRest/Schema/Schema.cs

Added Generate Contract api support

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Loans/FieldDescriptor.cs
src/EncompassRest/Loans/LoanField.cs
src/EncompassRest/ModelPath.cs

Added attribute path support

---

src/EncompassRest/Loans/FieldReader/LoanFieldReader.cs
src/EncompassRest/Loans/FieldReader/LoanFieldValue.cs
src/EncompassRest/Loans/LoanApis.cs

Disabled field reader support as Ellie Mae has removed access to the API.

Disabled field reader support

---

src/EncompassRest.Tests/BorrowerPairsTests.cs
src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Loans/Apis/BorrowerPairs.cs
src/EncompassRest/Loans/EntityCustomizations.cs

Uses `Id` instead of `ApplicationId` now.
Closes #233

Fix application id issue.

---

src/EncompassRest/Loans/Documents/LoanDocument.cs

Added document conditions property.

---

src/EncompassRest.Tests/LoanConditionsTests.cs
src/EncompassRest/Loans/Conditions/UnderwritingCondition.cs

OwnerRole isn't a string rather an EntityReference.

fixed OwnerRole in underwritingConditions

---

src/EncompassRest.Tests/JsonHelperTests.cs
src/EncompassRest/Utilities/JsonHelper.cs

Fixed `ArgumentOutOfRangeException` when populating with duplicate id's

Fixed ArgumentOutOfRangeException when populating with duplicate id's

---

src/EncompassRest.EntityGenerator/EntityGenerator.cs
src/EncompassRest.Tests/SchemaTests.cs
src/EncompassRest/.editorconfig
src/EncompassRest/ClientParameters.cs
src/EncompassRest/CommonCache.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Loans/Enums/FanniePropertyFormType.cs
src/EncompassRest/Loans/Enums/FreOfferingIdentifier.cs
src/EncompassRest/Loans/Enums/PropertyValuationMethodType.cs
src/EncompassRest/Loans/Enums/SectionOfActType.cs
src/EncompassRest/Loans/FieldDescriptor.cs
src/EncompassRest/Loans/LoanFieldDescriptors.cs
src/EncompassRest/Loans/LoanFieldMappings.cs
src/EncompassRest/Loans/LoanFieldPatternMappings.cs
src/EncompassRest/Schema/FieldOption.cs

Added support for refreshing standard fields.
Newly added fields will show up as well as any model path or description changes will be reflected.
Closes #216.

Added support for refreshing standard fields.

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Loans/CreateLoanOptions.cs

Added support for assigning a loan officer to a loan on creation.

Added support for assigning a loan officer to a loan on creation

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Loans/CustomLoanField.cs
src/EncompassRest/Loans/LoanField.cs

Add ability to assign a field directly to another field's value.

Add ability to assign a field to another field's value

---

src/EncompassRest.EntityGenerator/EntityGenerator.cs
src/EncompassRest/Loans/SelfEmployedIncome.cs

Changed SelfEmployedIncome.FieldValue to a string type

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/TestBaseClass.cs
src/EncompassRest/ClientParameters.cs
src/EncompassRest/EncompassRestClient.cs
src/EncompassRest/Loans/LoanFieldDescriptors.cs
src/EncompassRest/Loans/LoanFields.cs
src/EncompassRest/UndefinedCustomFieldHandling.cs

Added support for undefined custom field handling

Added support for undefined custom field handling

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/ApiObject.cs
src/EncompassRest/Loans/ImportFileType.cs
src/EncompassRest/Loans/Loans.cs

Added Loan Import from File API Support

---

src/EncompassRest.EntityGenerator/EntityGenerator.cs
src/EncompassRest.Tests/EncompassRest.Tests.csproj
src/EncompassRest.Tests/TestBaseClass.cs
src/EncompassRest/Company/Users/Rights/CollateralTrackingRights.cs
src/EncompassRest/Company/Users/Rights/LoanProgramsRights.cs
src/EncompassRest/Company/Users/Rights/PersonalTemplatesRights.cs
src/EncompassRest/Company/Users/Rights/ToolsRights.cs
src/EncompassRest/EncompassRest.csproj
src/EncompassRest/Loans/FieldDescriptor.cs
src/EncompassRest/Utilities/EnumJsonConverter.cs

Upgraded the referenced version of Enums.NET.
Fixed rights deserialization due to schema changes.
Closes #304

Upgraded the referenced version of Enums.NET

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Loans/LoanMetadata.cs

Added the two new properties for LoanMetadata.
Closes #309

Added the two new properties for LoanMetadata

---

src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/Webhook/WebhookResourceEvent.cs

Added explicit support for the move loan event webhook.
Closes #310

Added explicit support for the move loan event webhook

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest/Loans/LoanField.cs
src/EncompassRest/Loans/LoanFields.cs
src/EncompassRest/Loans/VirtualLoanField.cs

Add flag to allow setting read-only field values for local purposes.

---

src/EncompassRest.Tests/EncompassRest.Tests.csproj
src/EncompassRest/EncompassRest.csproj
src/EncompassRest/EncompassRestException.cs

Updated the default exception message to include the status code and correlation id.
Incremented version number to v1.2

Updated the default exception message and updated version to v1.2

---

src/EncompassRest/NA.cs

Add support for "N/A" in NA<decimal> type

---

src/EncompassRest/EncompassRest.csproj
src/EncompassRest/NA.cs

Fix NA<decimal> deserialization for alternative forms.

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/WebhookTests.cs
src/EncompassRest/EncompassRest.csproj
src/EncompassRest/Loans/LoanFieldMappings.cs
src/EncompassRest/Loans/LoanFieldPatternMappings.cs
src/EncompassRest/ModelPath.cs
src/EncompassRest/Webhook/Webhook.cs
src/EncompassRest/Webhook/WebhookEvent.cs
src/EncompassRest/Webhook/WebhookEventOptions.cs
src/EncompassRest/Webhook/WebhookEventPayload.cs
src/EncompassRest/Webhook/WebhookStatus.cs

Added support for Webhook Event History

---

src/EncompassRest.Tests/LoanTests.cs
src/EncompassRest.Tests/MismoExportTests.cs
src/EncompassRest/ApiObject.cs
src/EncompassRest/Loans/LoanApis.cs
src/EncompassRest/Services/MismoFormat.cs
src/EncompassRest/Services/Services.cs

Added Mismo export support

---

src/EncompassRest/Loans/Correspondent.cs
src/EncompassRest/Loans/Employment.cs
src/EncompassRest/Loans/ReoProperty.cs
src/EncompassRest/Loans/Residence.cs

I updated values that were previously integers to decimal that 22.3 now uses.

Updated 22.3 integer values to decimal
